game_text_en:
  version: "jak1-v2"
  group-name: "common"
  languages:
    - en:
        id: 0
    - en_GB:
        id: 6
game_text_de:
  version: "jak1-v2"
  group-name: "common"
  languages:
    - de:
        id: 2
game_text_ja:
  version: "jak1-v2"
  group-name: "common"
  languages:
    - ja:
        id: 5
